civo/kubernetes-marketplace

- openfaas/manifest.yaml
- openfaas/post_install.md
The hash is no-longer required due to the creation using an
environment variable instead of a YAML file.
The post-install instructions are also updated to mention
the password being in the UI and the NodePort being used.
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
> Remove password hash

- jenkins/app.yaml
- jenkins/post_install.md
Pod gets stuck in `ContainerCreating` state. After referencing Racher's docs, only `PersistentVolumeClaim` is required.
changes:
- fix service name and port
- referenced longhorns example and noticed that only PersistentVolumeClaim section is needed (https://github.com/longhorn/longhorn/blob/master/examples/deployment.yaml)
> Fix volumes and rename service name

- prometheus-operator/app.yaml
- prometheus-operator/install.sh
- prometheus-operator/manifest.yaml
* Upgrade helm chart from `6.20.3` to `8.2.0` and update the app version in the Civo manifest
* Update CRD's to reflect the new helm chart version
* Add bash loop to check for CRD's to exist before installing the chart
running chart externally with helm3 (rather than install tiller for testing):
```bash
~ % helm3 list
NAME               	NAMESPACE 	REVISION	UPDATED                                	STATUS  	CHART                    	APP VERSION
prometheus-operator	monitoring	1       	2019-11-15 12:56:06.365987947 -0500 EST	deployed	prometheus-operator-8.2.0	0.34.0   
```
----
Updated chart with servicemonitors working will now show actual data in prom/grafana:
> Upgrade prometheus-operator chart

- postgresql/app.yaml
The psotgres app was missing an env var that defined
where the data directory should be, looks like the
underlying volume had a lost+found dir
(linux root dir thing) that meant that postgres init
script failed to run
Signed-off-by: Alistair Hey <alistair@heyal.co.uk>
> Fix Postgres app - missing env var

- rancher/app.yaml
Currently, there is a bug in the Rancher 2.3.0 which causes errors when a user wants to view the `local/system` project. 
It has been fixed in the 2.3.2. Here you can find more details: https://github.com/rancher/rancher/issues/23613#
But I think it's always a good idea to update apps to the latest version.
Here is the screenshot with updated application. 
It's probably something for @saiyam1814 (maintainer) or @andyjeffries (last contributor) to review. Thanks.
> Upgrade the rancher app to 2.3.5

- helm/app.yaml
- helm/manifest.yaml
Helm 2.16.0 introduced Kubernetes 1.16 compatibility and I am unaware of any breaking change in 2.16 from 2.14. Whilst it would be a good idea to go to Helm 3, that is obviously a much more disruptive change.
Screenshot of Helm 2.16.5 running in my Civo k3s cluster:
> Upgrade Helm to 2.16.5. Closes #39.

- kubernetes-dashboard/app.yaml
An update to the dashboard app (or possibly another reason) removed the admin-user ServiceAccount and ClusterRoleBinding that allowed a user to log in to the dashboard using a secret token. This update adds back the SA and CRB to allow the commands in post-install.md to work.
> Add admin-user back

- keptn/install.sh
This fixes the prompt that was blocking the installation.
Providing an empty `creds.json` file will skip this prompt during the installation procedure
> fix Keptn installation

- traefik2/app.yaml
A missing service account have been included in the traefik v2 app.yaml. Not sure how it was missed but nevertheless here it is!  
Also specified the service account on the traefik DaemonSet spec so that it have the correct account when searching for the resources.
> Fixed missing service account.

- traefik2/manifest.yaml
The value `2.3` is parsed as a number in yaml, rather than version string, changed it to an explicit string type.
> Minor fix to the traefik v2 manifest

- wordpress/app.yaml
The civo-init.sh was wrongly created without escape some characters.
> Fixed Wordpress init container

- wordpress/post_install.md
When following the original post-install instructions an error was displayed about `let` not found.
The script requires more than regular `sh` commands, running it with `bash` succeeds.
> WP post-install - bash instead of sh

- README.md
- falco/manifest.yaml
- haproxy/manifest.yaml
Fixes: ```Error: json: cannot unmarshal number into Go struct field KubernetesMarketplaceApplication.version of type string```
Values of x.y are cast to int by the API which breaks the go client
> Fix None String Versions, breaking CIVO API

- cert-manager/install.sh
With the new method of running clusters in Civo, the control planes nodes no longer have access to general nodes. As such, the cert-manager web hooks are not accessible.
This change removes the web hooks after install 
References:
- https://github.com/jetstack/cert-manager/issues/3645
> Disable CertManager web hooks

- cert-manager/manifest.yaml
Helm hasn't been used for cert-manager since 62a2aac338dd263ef96086587c2fc619bf45c5de and I really don’t want tiller in my cluster 😀
> fix: remove Helm dependency from cert-manager

- istio/install.sh
- istio/uninstall.sh
Fixing the assumptions on script execution directory 
- script and its file will use relative dir of install.sh script 
- use curl over wget to avoid writing temp files 
- add `sSL` to curl to show errors in case of failures
> Istio fixes

- flux/install.sh
- flux/post_install.md
This is just a change which fixes the URL of `toolkit.fluxcd.io` to just `fluxcd.io`.
Test:
```sh
curl -Is https://fluxcd.io/install.sh
HTTP/2 200
accept-ranges: bytes
cache-control: public, max-age=0, must-revalidate
content-length: 5600
content-type: application/x-shellscript
date: Sun, 25 Jul 2021 18:13:47 GMT
strict-transport-security: max-age=31536000
age: 3260
etag: "910be6a0f291257fc5e2534e74d4b28b-ssl"
server: Netlify
x-nf-request-id: 01FBFH2FF51VCK26W15655FEGS
```
@stefanprodan this fixes #229 .
> fix FluxCD URLs

- reloader/install.sh
My proposal is change kubectl create namespace command to add flag in helm command `--create-namespace` to code be more readable.
> create namespace in helm via flag

- traefik2/app.yaml
- traefik2/manifest.yaml
- traefik2/post_install.md
This PR include the following changes to the traefik2 marketplace app:
* Traefik was updated to version 2.5 (from 2.3).
* The default metrics port was changed from 8080 to 9000 (more standard for metrics) to enable easier access to api/dashboard.
* Documentation was updated with information on how to access the dashboard.
> fix: traefik2 metrics and dashboard.

- traefik2/app.yaml
* Updated CRDs to v1 from v1beta1 (required for newer Kubernetes versions).
* Updated RBAC to contain new resources (middlewaretcps, serverstransports).
* Updated daemonset to allow cross-namespace and external name services (which was default earlier).
> Fix(Traefik2): Updated CRDs to v1 instead of v1beta1.

- helm/app.yaml
The gcr.io image keeps failing upon getting pulled from the registry. Proposed solution is to change the registry to helmpack/tiller (dockerhub). Changed the veriosn from `v2.16.5` to `v2.16.12` because it is the latest tag in the image
> Fix ImagePullBackoff failing tiller-deploy

- argo-workflows/Makefile
- argo-workflows/app.yaml
- argo-workflows/config
The container runtime executor for workflows defaults to docker.
Since Civo kubernetes is based on k3s, containerd is used instead
of docker. So jobs submitted to workflows fail unless the container
rutime executor is updated to pns(process namespace sharing)
Signed-off-by: Sibu Thomas Mathew <sibuthomasmathew@gmail.com>
```bash
$ kubectl get nodes
NAME                                                     STATUS   ROLES    AGE   VERSION
k3s-accure-workflow-cluster-776d-63c6ae-node-pool-1b25   Ready    <none>   10m   v1.20.2+k3s1
k3s-accure-workflow-cluster-776d-63c6ae-node-pool-7a04   Ready    <none> …
```
> fix: Change Argo Workflows executor

- wordpress/post_install.md
I have installed latest version of Wordpress to my fresh new cluster, and after install it went into a CrashLoopBackOff, because readiness probe had some issue. After i extended my `wp-config.php` it gone.
> Fix wordpress pod goes into a CrashLoopBackOff loop after install

- README.md
---
Change to the testing docs. The tells us to use `--app` in the docs, but the flag is `--applications` in the latest version (1.0.26) of the CLI app
> [docs]: change `--app` to `--applications` in testing section

- kubevela/install.sh
- kubevela/manifest.yaml
- kubevela/post_install.md
Signed-off-by: Qiaozp <qiaozhongpei.qzp@alibaba-inc.com>
Install VelaUX by default so that user can have a quick start.
> Bump KubeVela: Install Velaux by default

- traefik2-nodeport/manifest.yaml
- traefik2-nodeport/post_install.md
> Update traefik v2 ingresss spec example to reflect changes made in k8s 1.23.x. 

- epinio/install.sh
- epinio/manifest.yaml
Yesterday Epinio v1.4.0 was released: https://github.com/epinio/epinio/releases/tag/v1.4.0
Updating the Epinio app to the latest version, and also pinning the helm-chart version to the one matching the 
CIVO manifest.yaml file, to avoid unexpected releases.
> Update Epinio 1.4.0

- .github/workflows/updatecli.yml
Skip "UpdateCLI" on forks.  Observed an error when updating [my fork](https://github.com/ssmiller25/kubernetes-marketplace/actions/runs/4461108999/jobs/7834706211#logs).  For now, easier to skip this step on Forks as I assume the targeting applications in this particular action will be maintained by Civo directly.  While normally someone who forks will disable actions, if they do not it will result in failed running attempts in their repo.
> Skip UpdateCLI Github Action on Forks

- .github/updatecli/updatecli.d/argocd.yaml
While looking at the Updatecli pipeline, I noticed that I made a mistake, the argocd pipeline will never work because it uses the app version instead of the chart version to verify that the latest argocd cd chart version is available on the Helm chart registry
```
CONDITIONS:
===========
chart
-----
✗ Helm Chart 'argo-cd' isn't available on https://argoproj.github.io/argo-helm for version 'v2.6.7'
=> expected condition result false, got false
```
and it should be 
```
CONDITIONS:
===========
chart
-----
✔ Helm Chart 'argo-cd' is available on https://argoproj.github.io/argo-helm for version '5.28.0'
```
> Argocd update pipeline should uses the chart version

- ferretdb/app.yaml
- ferretdb/manifest.yaml
- ferretdb/post_install.md
- This PR provides a configuration for FerretDB 1.0. 
- The pod with the app consists of two containers: FerretDB itself and a separate PostgreSQL container. This approach follows the [official FerretDB documentation](https://docs.ferretdb.io/quickstart-guide/docker/).
- Only FerretDB's port (`27017`) is exposed as service port.
---
Existing Marketplace application checklist:
> Update FerretDB to version 1.0

- kubevela/install.sh
- kubevela/manifest.yaml
This PR Bump KubeVela to its first major version (1.0.0) in civo marketplace with following components:
- KubeVela core 1.9.4
- VelaUX 1.9.2
Fixes: #485
> Feat: bump KubeVela to 1.9.4

- .github/updatecli/updatecli.d/jenkins.yaml
This pullrequest adds an updatecli manifest to automate Jenkins helm chart update when a new version is published.
Manifest tested on https://github.com/olblak/kubernetes-marketplace/pull/23
> Automate Jenkins version update

- kong-ingress-controller/install.sh
- kong-ingress-controller/manifest.yaml
- kong-ingress-controller/post_install.md
Fixes #495 
Updating Kong Ingress Controller to latest 2.11 version.
> Updating Kong Ingress Controller version to latest 2.11

- ambassador-edge-stack/install.sh
- ambassador-edge-stack/manifest.yaml
- ambassador-edge-stack/post_install.md
- ambassador-edge-stack/uninstall.sh
Updated Ambassador Edge Stack to latest 3.8.0 version.
Also successfully tested the application routing.
> Updating Ambassador Edge Stack version to latest 3.8.0

- traefik2-nodeport/manifest.yaml
For the new marketplace installation, we need to have the app name match the folder name
> Traefik: update manifest.yaml

- .github/updatecli/updatecli.d/cert-manager.yaml
This pullrequest updates the Updatecli manifest for cert-manager to monitor a different "latest" cert-manager version.
To avoid futur pullrequest like this one https://github.com/civo/kubernetes-marketplace/pull/604
As I explain in the comment, the cert-manager project maintains multiple release line and we want to be sure to pick
the latest one based on semantic versioning rules and not the latest released.
They are different ways to understand the meaning of "latest" and I think in this particular situation semantic versioning seems to better. Another option would be to only monitor GitHub release tagged "latest"
> fix(updatecli): always use latest cert-manager using semver

- .github/updatecli/updatecli.d/rancher.yaml
- rancher/install.sh
Fix Rancher version deployed
I don't know when or how but apparently a `rc-3` crept in the Rancher version.
This pull request modifies the rancher installation script to rely on a variable which is easier to update with a regex
> fix: remove rc version from Rancher

- jenkins/install.sh
Hi @saiyam1814. I think the installation script doesn't work anymore. I tried creating new kubernetes cluster with jenkins installed and I found an error.
```
{"time":"2024-04-19T14:42:29.691030802Z","level":"INFO","msg":"Command output","stdout":"\"jenkins\" has been added to your repositories\nHang tight while we grab the latest from your chart repositories...\n...Successfully got an update from the \"jenkins\" chart repository\nUpdate Complete. ⎈Happy Helming!⎈\nnamespace/jenkins created\n"}
{"time":"2024-04-19T14:42:29.691166777Z","level":"ERROR","msg":"Command output","stderr":"Error: INSTALLATION FAILED: execution error at (jenkins/templates/deprecation.yaml:129:6): `controller.adminUser` no longer exists. It has been renamed to `controller.admin.username`\n"}
Error: exit status 1 …
```
> Update jenkins install.sh with the correct keys

- traefik2-loadbalancer/app.yaml
- traefik2-loadbalancer/manifest.yaml
- traefik2-loadbalancer/post_install.md
* Correct spelling mistakes in post-install readme
* Add missing CRD definitions
* Sync roles to traefik 2.11 examples while keeping custom civo naming
> traefik2-loadbalancer: Upgrade to v2.11.1; resolves #734

- traefik2-loadbalancer/post_install.md
Updating the post install steps for traefik LB, as the ingress YAML was invalid.
> updated ingress yaml to be valid for current k8s versions

- cyclops/manifest.yaml
marketplace-installer fails to start Cyclops with
```
Error: stat /tmp/prefix/cyclops-ui: no such file or directory
```
My guess is that the manifest name (`cyclops-ui`) and folder name (`cyclops`) do now match. PR updates manifest name to `cyclops`. Let me know if the better approach is to rename the folder or something else is at fault\
> fix cyclops manifest name

- spinkube/install.sh
- spinkube/manifest.yaml
- spinkube/uninstall.sh
I haven't tested this yet (was testing something else on Civo and remembered we cut a release last week), but I can do so later.
[Changelog](https://github.com/spinkube/spin-operator/releases/tag/v0.2.0), the main new feature being ensuring that SpinApps have TLS certs for outbound connections: https://github.com/spinkube/spin-operator/pull/207
> spinkube: bump to 0.2.0

- cyclops/install.sh
- cyclops/manifest.yaml
- cyclops/uninstall.sh
> bump Cyclops to v0.11.1

- flux/post_install.md
This PR removes the empty trailing list item which causes the final link to render incorrectly as a heading
> Remove trailing list item

- postgresql/post_install.md
Why the changes: When you install the postgres via the marketplace, there's no way to remove it. The feeling of installing something and having no way to remove it is not a very good one.
> Add remove instructions to postgres

- .circleci/config.yml
looks like it needs a new ruby version
🔴 requires 3.1.0 currently 3.0.0
- https://app.circleci.com/pipelines/github/civo/kubernetes-marketplace/6481/workflows/ddf74b91-c590-44c9-89fa-ade8bc1cfe6e/jobs/6439?invite=true#step-103-65_90
🟢 change passes
- https://app.circleci.com/pipelines/github/civo/kubernetes-marketplace?branch=pull%2F1004
> bump required ruby version 3.1.0

- traefik2-nodeport/app.yaml
- traefik2-nodeport/post_install.md
**Background:**
It fixes one recent issue reported by an user, in which he tried to install `node-exporter` in the k8s cluster, which by default uses port 9100, and since `Traefik2-nodeport` already uses that port, he wasn't able to install `node-exporter`.
**What I have done?**
I changed it to use a less common port 9910, it is less likely to conflict with other applications.
**Simple ways to reproduce the issue:**
1. Create a `traefik-config.yaml`, put in the config. [here](https://github.com/civo/kubernetes-marketplace/blob/b3fd86c23fec4e385bda606824eddb2f3e474309/traefik2-nodeport/app.yaml)
2. Do `kubectl apply -f traefik-config.yaml`
3. Create `daemonset.yaml`:
```yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
labels:
app.kubernetes.io/component: exporter
app.kubernetes.io/name: …
```
> Fix: make Traefik2-nodeport to use a different port than 9100
