- openfaas/manifest.yaml
Updated the version and the blurb to match other marketplace
entries.
Signed-off-by: Alex Ellis (OpenFaaS Ltd) <alexellis2@gmail.com>
> Bump version for OpenFaaS

- prometheus-operator/install.sh
> Update prometheus-operator helm chart version

- cert-manager/install.sh
- cert-manager/manifest.yaml
- cert-manager/post_install.md
Upgrade cert-manager to 0.11.  Also pointing documentation to specific version, in case "latest" changes before the manifest upgrades in the marketplace.
> Upgrade cert-manager

- klum/app.yaml
- klum/post_install.md
* KLUM was broken as a marketplace application due to variable expansion in the application manifest. This is simply due to me not being able to test this part of the deployment locally.
* Fixed the documentation code blocks
> Fix KLUM variable expansion

- prometheus-operator/app.yaml
- prometheus-operator/manifest.yaml
> Upgrade prometheus-operator to chart v8.7.0

- klum/app.yaml
This is a follow up to the previous PR with another shot at expanding the variable. This time trying a simple str replacement rather than bash style expansion.
> Fix Klum var expansion

- klum/app.yaml
Hopefully the last PR to get this app working. when the user fetches a kubeconfig the server name needs to be a https endpoint.
> Klum var templating

- prometheus-operator/manifest.yaml
It's not needed if using HelmChart CRD
> Remove dependency on helm app

- kubernetes-dashboard/app.yaml
- kubernetes-dashboard/manifest.yaml
* [x ] Have you followed the guidelines in our Contributing document in setting up the application?
* [x ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
* [ x] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
Update k8s dashboard to v2.0 stable version
cc @morganlaneap
> Update k8s dashboard

- rancher/app.yaml
> Changing version to stable

- docker-registry/install.sh
> Fixed error in the install.sh

- docker-registry/manifest.yaml
> docs: Fix Docker Registry listing typo

- prometheus-operator/app.yaml
> include namespace in prometheus-operator

- longhorn/app.yaml
- longhorn/manifest.yaml
Update longhorn to latest available. v0.7.0 is a bit too old now.
Signed-off-by: shubhindia <shubhindia123@gmail.com>
> update longhorn version to v1.0.2

- metrics-server/post_install.md
> Fix markdown heading error

- portainer/app.yaml
- portainer/manifest.yaml
- portainer/post_install.md
Signed-off-by: Saiyam Pathak <saiyam@civo.com>
Issue - #79 
* [* ] Have you followed the guidelines in our Contributing document in setting up the application?
* [ *] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [*] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [ *] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
> portainer version update and ingress change

- cert-manager/install.sh
- cert-manager/manifest.yaml
- cert-manager/post_install.md
- cert-manager/uninstall.sh
fixes #14 
Update marketplace to the 1.0.2 version of cert-manager, now that they released a stable version.
> install cert-manager version 1.0.2

- .gitignore
- tekton/Makefile
- tekton/README.md
- tekton/app.yaml
- tekton/manifest.yaml
Update tekton to 1.17.0, and some additional changes to the build tooling.
> Tekton 1.17.0 Update

- wordpress/app.yaml
- wordpress/post_install.md
* Init container added to simplify SSL configuration behind a reverse proxy
* Modify post_install.md to document SSL configuration and Ingress modification
> WordPress init container to simplify SSL configuration

- bin/lint_all.sh
- bin/lint_name.rb
- jenkins/manifest.yaml
> name whitespace check

- ghost/post_install.md
Add step to : 
- Create admin user.
- Delete default user created by ghost.
- Create your first blog.
> ghost : add new how to in post-install

- wordpress/app.yaml
- wordpress/manifest.yaml
* Wordpress version updated to 5.5.3
* Improved civo-init.sh to avoid problems with SSL
---
> Wordpress 5.5.3

- longhorn/post_install.md
Based on [thread in Civo Slack Channel](https://civo-community.slack.com/archives/CMVCKMCN5/p1604507361421600?thread_ts=1604494315.400000&cid=CMVCKMCN5) updating post-install instructions with a simpler method to leverage longhorn volumes.  Also adjusting existing yaml to work with a new cluster (no assumed namespaces)
___ 
> Additional longhorn usage examples

- litmuschaos/manifest.yaml
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (chore)litmuschaos: update the category to ci_cd

- bitwardenrs/app.yaml
- bitwardenrs/manifest.yaml
- bitwardenrs/post_install.md
- joomla/manifest.yaml
> Added bitwardenrs app

- cert-manager/install.sh
> use simplified 1.2.0 cert-manager installation instead

- wordpress/app.yaml
* WordPress updated to v5.6
---
> WordPress updated to v5.6

- nodered/app.yaml
- nodered/post_install.md
* Node-RED version updated to v1.2.7
* Advice about Authentication included in post_install.md
---
> Node-RED updated to v1.2.7

- gitea/app.yaml
This includes an upgrade to latest chart version which also includes upgrade to latest stable Gitea version (which includes security fixes)
> Update Gitea to latest chart version (2.1.6)

- nodered/manifest.yaml
Updated nodered manifest.yaml to match app.yaml
> Updated nodered manifest.yaml

- rancher/post_install.md
> use networking.k8s.io/v1 version of Ingress for service exposure guide in Rancher

- haproxy/app.yaml
Updated HAProxy to latest version
> Updated app.yaml

- ghost/app.yaml
- ghost/post_install.md
- Update to the latest version 4.1.2
- Update `post_install.md`, include example patch to update image tag version
**Before update image**
**After update image**
> Update: ghost blog

- okteto/config.yaml
- okteto/install.sh
- okteto/manifest.yaml
> remove cert-manager as a dependency in okteto

- litmuschaos/install.sh
- litmuschaos/manifest.yaml
- litmuschaos/post_install.md
Signed-off-by: ksatchit <karthik.s@mayadata.io>
> (chore)litmuschaos: update litmus charts to 2.0beta

- okteto/install.sh
> check if ip is available before installing helm

- okteto/install.sh
- okteto/manifest.yaml
* [ x] Have you followed the guidelines in our Contributing document in setting up the application?
* [ x] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
> use CLUSTER_ID not CLUSTER_NAME

- okteto/config.yaml
Set the storage size of the okteto registry in the correct key
> set the storage size in the correct key

- kyverno/install.sh
- kyverno/manifest.yaml
@JimBugwadia 
#198 New Plan to make it possible to choose between the Default and Restricted Pod Security Standard and the audit or enforce mode for this policies.
> Plan for Pod Security Standard and Validation Failure Action

- tekton/Makefile
- tekton/app.yaml
- tekton/manifest.yaml
Update Tekton to the latest available version, 0.24.1.
Signed-off-by: Steve Miller <me@r15cookie.com>
Screenshot of dashboard:
Test with the framework below:
```sh
me@penguin:~/git/kubernetes-marketplace/tekton$ make clean
me@penguin:~/git/kubernetes-marketplace/tekton$ make build
Test final app.yaml for validity
Testing validity of app.yaml
Clean app.yaml generated
me@penguin:~/git/kubernetes-marketplace/tekton$ CIVO_KUBECONFIG=$PWD/kubeconfig.test make test
Applying manifest and test run
namespace/tekton-pipelines created
podsecuritypolicy.policy/tekton-pipelines created …
```
> Update tekton to 0.24.1

- keptn/install.sh
- keptn/manifest.yaml
- keptn/post_install.md
Updating the Keptn marketplace extension to the newest version (v0.8.2) as discussed with @jetzlstorfer.
> Update Keptn extension to V0.8.2

- loki/Makefile
- loki/app.yaml
- loki/manifest.yaml
- loki/post_install.md
Updating Loki to the latest version, and minor updates to make compatible with the updated Prometheus stack operator.
Thank you for wanting to submit a Pull Request to the Civo Kubernetes Marketplace repository! 
Testing Framework:
```sh
me@penguin:~/git/kubernetes-marketplace/loki$ make test-keep
Creating loki-test
The cluster loki-test (d9d833f7-0256-48b9-b5b7-622fb8e986d3) has been created in 1 min 36 sec
Waiting for all 3 nodes to come up
Test 1
Test 2
Test 3
Applying manifest and test run
namespace/loki created
helmchart.helm.cattle.io/loki created
job.batch/testjob created
Checking status of test run
Test 1
Test 2
Test 3
Test 4
Test 5
Test 6
Test 7
Success!
```
Screenshot in operational …
> Update Loki to 2.1.2

- istio/.gitignore
- istio/install.sh
- istio/manifest.yaml
- istio/post_install.md
- istio/uninstall.sh
Use default Istio installer `downloadIstio.sh` to install Istio.
@saiyam1814 ^^
> fix: use istio official downloader script

- istio/install.sh
* [ x] Have you followed the guidelines in our Contributing document in setting up the application?
* [x ] Have you checked that the application your submission is proposing to add does not yet exist on the Marketplace, or as a pull request to be processed?
* [x ] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
* [x ] Can you confirm that the software you are submitting licensed for use in a publicly-available Kubernetes marketplace?
Make the control plane in install.sh use github raw url
> use github url for control-plane install

- keptn/install.sh
Signed-off-by: jetzlstorfer <juergen.etzlstorfer@dynatrace.com>
> keptn marketplace integration

- postgresql/app.yaml
> [postgresql] set security context for volume mounts

- ghost/app.yaml
- ghost/manifest.yaml
What's change :
- Bump ghost version to 4.8.3
- Update manifest version to match the deployment spec.
> Update : change ghost version in manifest

- istio/install.sh
- istio/uninstall.sh
As the download takes time, adding a wait to make sure the download and related  tasks complete before proceeding futher
CC: @saiyam1814
> add a wait for downloadIstio to complete

- istio/.gitignore
- istio/install.sh
- istio/uninstall.sh
improving istio install to use full path names groked from the download logs
> grok istioctl path from download stdout

- gloo-edge/manifest.yaml
- istio/install.sh
- istio/manifest.yaml
Reverted the  manifest updates
- add echo for revision 
- updated email for istio and gloo
> manifest updates

- istio/install.sh
Using awk over native bash repalcement for revision string manipulation
> using awk for revision pattern replacement

- okteto/install.sh
- okteto/manifest.yaml
- okteto/post_install.md
> Update Okteto Enterprise to 0.9.6

- keda/install.sh
- keda/manifest.yaml
- keda/post_install.md
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
Update KEDA to version 2.4.0 
https://github.com/kedacore/keda/releases/tag/v2.4.0
Install:
Delete:
> Update KEDA to 2.4.0

- litmuschaos/install.sh
- litmuschaos/manifest.yaml
- litmuschaos/post_install.md
Signed-off-by: Soumya Ghosh Dastidar <gdsoumya@gmail.com>
> Updated litmus to 2.0.0 version

- kyverno/install.sh
- kyverno/unintall.sh
Signed-off-by: Frank Jogeleit <frank.jogeleit@web.de>
@JimBugwadia @realshuting
Installing the new Helm Repository for all Kyverno CRDs before Kyverno itself. This fix the current issue by installing the latest Kyverno helm release without CRDs.
> Add new Kyverno CRD HelmRepo

- cert-manager/install.sh
- cert-manager/manifest.yaml
> Bump cert-manager to 1.5.3

- CONTRIBUTING.md
This PR fixes a pronoun problem. Thanks!
> Grammar Correction for Contributing

- kubernetes-dashboard/app.yaml
- kubernetes-dashboard/manifest.yaml
Update K8s dashboard image version to v2.4.0
Screenshot below - Kubernetes dashboard running on civo k3s cluster.
> Kubernetes dashboard version update to v2.4.0

- vault/install.sh
- vault/manifest.yaml
Signed-off-by: relgisri <dennis@irsigler.cloud>
This PR just updates the Helm Chart Version used to the latest stable available.
Additionally I added the Hashicorp nameto the manifest, because this better reflects the common reference of the product.
> Update Vault version and name

- keda/install.sh
- keda/manifest.yaml
- keda/post_install.md
Update KEDA helm chart to version 2.5.0
https://github.com/kedacore/keda/releases/tag/v2.5.0
> chore: update KEDA to version 2.5.0

- ambassador/post_install.md
Fixes #282 
Documentation change, pointing to correct version of the ambassador docs.
> Fixes #282 pointing to correct version of ambassador docs

- fission/install.sh
- fission/manifest.yaml
- fission/uninstall.sh
Signed-off-by: Sanket Sudake <sanketsudake@gmail.com>
This PR updates the Fission version to minor release 1.15.1.
> Update Fission version to 1.15.1

- parca/app.yaml
- parca/parca-agent.yaml
- parca/parca.yaml
I am the maintainer for Parca both on Parca's side but also on here and this is merely a version upgrade. :)
> Update Parca to v0.6.1 and Parca Agent to v0.3.0

- okteto/install.sh
This solves a reported issue where the certificates were never online due to a mismatch on the CRD version between the latest version of the Okteto Enterprise helm chart, and the one used here.
> Okteto Enterprise - pin the CRD version

- keda/install.sh
- keda/manifest.yaml
- keda/post_install.md
> chore: update KEDA to version 2.6.0

- traefik2-nodeport/app.yaml
> Update traefik2-nodeport to bind to 80/443 correctly

- kubesphere/manifest.yaml
- kubesphere/post_install.md
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
There are some typos in KubeSphere, and it's very important we need to change `Kubesphere` to `KubeSphere`.
> docs: fix some typos in KubeSphere

- kubesphere/app.yaml
- kubesphere/install.sh
Apply clusterconfiguration with stdin instead of a remote file, and change node_exporter's port to `9101` to solve port conflict.
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
@FeynmanZhou @saiyam1814 @pixiake 
The test screenshot like below, please have a  look if you have free time.
> bugfix: solve node_exporter port conflict

- traefik2-nodeport/post_install.md
> Documentation and Markdownlint Updates

- keda/install.sh
- keda/manifest.yaml
> chore: patch update of keda

- kyverno/install.sh
- kyverno/manifest.yaml
- kyverno/unintall.sh
Hi @saiyam1814, I tested the the install it worked fine, I just took the chance and updated the version to patch 1.6.2
Fixes #301
> chore: update kyvnero to 1.6.2

- .gitignore
- haproxy/post_install.md
> updated ingress doc for haproxy

- parca/app.yaml
- parca/manifest.yaml
- parca/parca-agent.yaml
- parca/parca.yaml
I am the maintainer of this application, both for Polar Signals writing Parca and also maintaining this marketplace app. 
The `app.yaml` was tested against a freshly installed CIVO earlier today.
> Update Parca to v0.11.1 and Parca-agent to v0.8.2

- fission/install.sh
- fission/manifest.yaml
- fission/uninstall.sh
Signed-off-by: Sanket Sudake <sanketsudake@gmail.com>
This PR updates the Fission version to release 1.16.0.
> Update Fission version to 1.16.0

- argocd/install.sh
- argocd/manifest.yaml
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
> chore: Update ArgoCD to version v2.4.2

- kyverno/install.sh
- kyverno/manifest.yaml
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
> chore: Update kyverno to version 1.7.1

- keda/install.sh
- keda/manifest.yaml
Signed-off-by: Engin Diri <engin.diri@mail.schwarz>
> chore: Update KEDA to version 2.7.1

- kubesphere/app.yaml
- kubesphere/install.sh
- kubesphere/manifest.yaml
Signed-off-by: mango <xu.weiKyrie@foxmail.com>
- Make yamllint and fix typo
- Update kubesphere to 3.3.0
> Update kubesphere to 3.3.0

- selenium/manifest.yaml
The current address (https://www.seleniumhq.org) is redirecting to https://www.selenium.dev, so this just avoids that redirect.
> Updated URL in manifest to avoid a redirect

- epinio/install.sh
- epinio/manifest.yaml
Updating the Epinio app to the latest version: https://github.com/epinio/epinio/releases/tag/v1.5.1
> Update Epinio to `1.5.1`

- keda/install.sh
- keda/manifest.yaml
> chore: update keda to 2.8.1

- kyverno/install.sh
- kyverno/manifest.yaml
> chore: update kyverno to 1.8.2

- longhorn/install.sh
- longhorn/manifest.yaml
> chore: update Longhorn to 1.3.2

- reloader/install.sh
- reloader/manifest.yaml
> chore: update reloader to v0.0.125

- argocd/install.sh
- argocd/manifest.yaml
> chore: update argocd to v2.5.3

- civo-cluster-autoscaler/uninstall.sh
Adds uninstall script for Civo Cluster Autoscaler.
> Add uninstall bash script for cluster-autoscaler

- kubesphere/post_install.md
A 404 error was generated when navigating to the 'port-firewall' link on this install doc. Located and update the link itself
> Update broken doc link

- openfaas/post_install.md
As the Slack link no longer works (and an alternate can not be found), I've pointed this link to the OpenFaaS Community page instead.
> Changed OpenFaaS Slack link to Community page

- metrics-server/post_install.md
The additional tutorial which was linked is no longer available and no redirects or alternate links can be found.
> Removed link to OpenFaas Guide which no longer exists

- epinio/install.sh
- epinio/manifest.yaml
Update Epinio to [v1.5.2](https://github.com/epinio/epinio/releases/tag/v1.5.2).
---
Ref: https://github.com/epinio/epinio/issues/1966
> chore: update Epinio to 1.5.2

- apisix-ingress-controller/install.sh
- apisix-ingress-controller/manifest.yaml
* bump to the latest version
* set loadbalancer mode is used by default
Signed-off-by: Jintao Zhang <zhangjintao9020@gmail.com>
> chore: Update APISIX Ingress Helm chart to v1.1.0

- keda/install.sh
- keda/manifest.yaml
> chore: update keda to 2.9.2

- argocd/install.sh
- argocd/manifest.yaml
> chore: update ArgoCD to v2.5.7

- parca/app.yaml
- parca/manifest.yaml
- parca/parca-agent.yaml
- parca/parca.yaml
Update to Parca v0.15.0 and Parca Agent v0.12.0. 
I've verified the installation of `app.yaml` working on `Server Version: v1.23.6+k3s1`
> Update to Parca v0.15.0 and Parca Agent v0.12.0

- epinio/install.sh
- epinio/manifest.yaml
Update Epinio to [v1.6.2](https://github.com/epinio/epinio/releases/tag/v1.6.2).
> chore: update Epinio to 1.6.2

- percona-monitoring-and-management/install.sh
Fixes
- Misplaced quotation marks
- Escape the PMM_ADMIN_PASSWORD value in curl call. Passwords may contain special characters that are messing up the curl call when they're not escaped. 
> Update PMM install.sh

- acorn/app.yaml
- acorn/manifest.yaml
Hi, 
I am already maintaining the AUR (Arch User Repository) package of `acorn` (see [the repo page](https://aur.archlinux.org/packages/acorn-cli)) and wanted to help maintain Acorn on Civo Cloud as well.
With this PR I propose two changes:
* version bump to `v0.5.1` (see Acorn's [release page](https://github.com/acorn-io/acorn/releases/tag/v0.5.1))
* Introduce two `plans`
* one **without** Auto TLS via Let's Encrypt
* one **with** Auto TLS via ACME, using the provided `CIVO:EMAIL_ADDRESS` variable to register with Let's Encrypt.
CC @saiyam1814 
I tested both plans with hard-coded variables on a Civo cluster. No screenshots provided since acorn doesn't expose any UI.
> feat: Update and enhance acorn marketplace application

- percona-monitoring-and-management/install.sh
- percona-monitoring-and-management/manifest.yaml
> Updated PMM to 2.35

- acorn/app.yaml
- acorn/manifest.yaml
No changes apart from the version bump.
> Bump Acorn version

- civo-cluster-autoscaler/app.yaml
Update autoscaler app to civo standard minimum size
> Update autoscaler app to civo standard minimum size

- polaris/app.yaml
- polaris/manifest.yaml
This is an update to the much newer, latest version of Polaris.
---
> Update polaris to latest version 7.2.0

- tekton/Makefile
- tekton/app.yaml
- tekton/manifest.yaml
- tekton/test-manifests/1-task.yaml
- tekton/test-manifests/2-taskrun.yaml
Tekton Update 2023.  Moving to the Tekton LTS version, which is supported for one year.
Test Results
```sh
coder@coder-ssmiller25-civo-marketplace:~/kubernetes-marketplace/tekton$ make test
Creating tekton-test
The cluster tekton-test (3223cafd-7a6c-4bae-9007-e07533909283) has been created in 5 min 56 sec
Applying manifest and test run
namespace/tekton-pipelines created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-controller-cluster-access created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-controller-tenant-access created
clusterrole.rbac.authorization.k8s.io/tekton-pipelines-webhook-cluster-access created
role.rbac.authorization.k8s.io/tekton-pipelines-controller created …
```
> Tekton Update 2023-03

- percona-monitoring-and-management/install.sh
- percona-monitoring-and-management/manifest.yaml
> Update PMM install script

- vault/install.sh
- vault/manifest.yaml
- vault/post_install.md
> feat: update Vault to 0.24.0 and add HA mode

- ferretdb/app.yaml
- ferretdb/manifest.yaml
- ferretdb/post_install.md
> Bump FerretDB to 1.2.1

- ferretdb/app.yaml
- ferretdb/manifest.yaml
> Update FerretDB to 1.3.0

- ferretdb/app.yaml
- ferretdb/manifest.yaml
> Update FerretDB to 1.4.0

- traefik2-loadbalancer/app.yaml
- traefik2-loadbalancer/manifest.yaml
- traefik2-nodeport/app.yaml
- traefik2-nodeport/manifest.yaml
> Bump traefik to new version

- traefik2-loadbalancer/app.yaml
- traefik2-nodeport/app.yaml
> Fix helm installation issues from traefik

- ferretdb/app.yaml
- ferretdb/manifest.yaml
> Bump FerretDB to 1.5.0

- ferretdb/app.yaml
- ferretdb/manifest.yaml
> Bump FerretDB version

- parca/app.yaml
- parca/parca-agent.yaml
- parca/parca.yaml
I'm the maintainer and did all things above.
> Update Parca to v0.18 and Parca Agent to 0.23.2

- kubevela/install.sh
- kubevela/manifest.yaml
**Changes**
There is a critical bug in vela 1.9.4, so this is a quick fix.
> Feat: bump KubeVela to 1.9.5

- loki/Makefile
- loki/app.yaml
- loki/app.yaml.tmpl
- loki/manifest.yaml
Update loki-stack to latest version, 2.9.11.  Addresses #524 
> Updated loki-stack to 2.9.11

- .gitignore
- tekton/Makefile
- tekton/app.yaml
- tekton/manifest.yaml
Updating Tekton to the latest version.  Addresses #520 
> Update Tekton to latest version

- gitlab/install.sh
- gitlab/manifest.yaml
> Update gitlab to the latest version

- sealed-secrets/app.yaml
- sealed-secrets/manifest.yaml
- sealed-secrets/post_install.md
> update sealed secrets to v0.23.1

- epinio/uninstall.sh
I am adding an uninstall scripts so I executed 
```
civo k8s application remove epinio -c mycluster
```
> Add uninstall script for Epinio

- selenium/manifest.yaml
> It's me.
> Fix missing CLUSTER_ID variable in manifest.
> I couldn't test this feature as it's a variable provided by Civo.
> No change, just enabling Ingress with URL.
> Fix missing CLUSTER_ID in manifest for Ingress

- gimlet/install.sh
- gimlet/manifest.yaml
- gimlet/post_install.md
This PR updates the ancient Gimlet version to the latest.
The script will always install the latest version going forward.
---
> Updating Gimlet

- gimlet/manifest.yaml
> Gimlet: fitting into 160 characters

- kubefirst/manifest.yaml
Until we pin the version, it will always be the latest one available from the Marketplace
> update the version to 'latest'

- metrics-server/manifest.yaml
Adds cluster type to metrics server as it is built-in app.
> Add cluster type to metrics server

- parca/app.yaml
- parca/parca-agent.yaml
- parca/parca.yaml
> Update to Parca v0.19 and Parca Agent v0.26

- traefik2-nodeport/app.yaml
Update app.yaml for making it generic install for k3s and Talos
> Update app.yaml for making it generic install for k3s and Talos

- traefik2-loadbalancer/app.yaml
- traefik2-loadbalancer/manifest.yaml
Traefik loadbalancer generic for k3s and talos
> Traefik loadbalancer generic for k3s and talos

- neuvector/post_install.md
This pull request updates the NeuVector name spelling and corrects some formatting.
Thank you for adding NeuVector!
n/a
> Update NeuVector verbiage and formatting

- kong-ingress-controller/install.sh
- kong-ingress-controller/manifest.yaml
- kong-ingress-controller/post_install.md
* The new version provides more stability, support for Gateway API, and some security updates.
* I used kong/ingress as the installation method, which is the recommended deployment method for the current project.
* PS: I am currently one of the maintainers of the Kong KIC project.
> kong: update to latest Kong KIC version

- dapr/manifest.yaml
Updating category for Dapr into the marketplace
> Update Dapr category on manifest.yaml

- bitwarden-unified/manifest.yaml
> updated name

- edp/install.sh
- edp/manifest.yaml
> chore: Update edp to version 3.7.5

- cerbos/install.sh
- cerbos/manifest.yaml
> chore: Update Cerbos to v0.34

- ferretdb/app.yaml
- ferretdb/manifest.yaml
* That PR refactors a single pod/deployment of FerretDB+PostgreSQL into two.
> Use separate pods for FerretDB and PostgreSQL

- edp/install.sh
- edp/manifest.yaml
- edp/post_install.md
> chore: Update EDP to the latest stable version

- spinkube/install.sh
- spinkube/pre_install.sh
> Install.sh fix 

- rqlite/install.sh
- rqlite/manifest.yaml
> rqlite 8.23.0

- dapr/install.sh
Keeping Dapr Release updated to stable latest
* [] Have you tested your application on the Civo managed Kubernetes service? Please include a screenshot.
> Upgrading Dapr to version 1.13.2

- kubernetes-external-secrets/install.sh
- kubernetes-external-secrets/manifest.yaml
> Bumping up kubernetes-external-secrets to latest 0.9.14 version

- spinkube/install.sh
- spinkube/manifest.yaml
- spinkube/post_install.md
@saiyam1814 - This is an update to the logic to wait for cert-manager installation.
> Update SpinKube to wait for cert-manager

- spinkube/uninstall.sh
This PR fixes #710 - adds uninstall script for spinkube
> Fixes #710 - Add uninstall script for spinkube

- projectsveltos/install.sh
- projectsveltos/manifest.yaml
> Upgrade Projectsveltos to v0.29.1

- passwordless.dev/manifest.yaml
> Update manifest.yaml for Passwordless

- bitwarden-passwordless-dev/manifest.yaml
> updated name to match folder

- bitwarden-passwordless-dev/manifest.yaml
* [ x] Notified the Maintainer of the application in this pull request so that they are aware of your proposal.
* [x ] Outlined the changes you are proposing, and the reasons these are required (e.g. stability, compatibility with new versions of Kubernetes implementations, etc).
* [x ] Tested that the application works with the proposed updates applied (including a screenshot).
* [x ] Updated the version number of the app if that has changed.
> Fix manifest description length

- reloader/install.sh
- reloader/manifest.yaml
> Issue:#522 Updated version Reloader to new

- cyclops/install.sh
- cyclops/manifest.yaml
- cyclops/post_install.md
- cyclops/uninstall.sh
> bump cyclops v0.10.0

- projectsveltos/install.sh
- projectsveltos/manifest.yaml
Moving to version v0.37.0 (from version v0.29.1) brings lot of new features
> deps: bump Projectsveltos to v0.37.0

- kubefirst/install.sh
- kubefirst/manifest.yaml
> upgrade kubefirst marketplace to v2.6.1

- kubefirst/install.sh
> changing konstruct charts host to our new permanent konstruct.io variation

- projectsveltos/install.sh
- projectsveltos/manifest.yaml
This version allows user to also start dashboard displaying information about all managed clusters.
> Update Sveltos to v0.40.0

- cyclops/install.sh
- cyclops/manifest.yaml
- cyclops/uninstall.sh
> bump Cyclops to v0.15.2

- kuberocketci/install.sh
- kuberocketci/manifest.yaml
- kuberocketci/post_install.md
> chore: Update KubeRocketCI to version 3.10.3

- cyclops/install.sh
- cyclops/manifest.yaml
- cyclops/post_install.md
- cyclops/uninstall.sh
Bump Cyclops to version `v0.18.1`. Also, Cyclops install script now uses the Helm chart for easier management.
> Cyclops to v0.18.1

- nginx/install.sh
> updating ingress-nginx version to mitigate cve

- kubefirst/install.sh
- kubefirst/manifest.yaml
> Upgrade kubefirst to v2.8.4 release
